### ISSUE TITLE
Imported models easily explode when physics are active

### ISSUE THREAD

**Issue by mardy** [TobyLobster/ImportLDraw#13]
Hi!
  Thanks for this importer, it's fantastic! :-) I'm having a little problem with the imported models though, and it might be that it's not actually something caused by ImportLDraw but rather Blender itself (or even on some mistakes of mine): if you select some connected pieces and then make them "active" from the physics tab, they'll "explode" once you run the animation.
My setup:
- scale when importing: 0.1
- the rigid body collision shape is set to "mesh"
- the sensitivity margin is set to 0 (I tried using a negative value, but Blender does not allow that)

Connecting the pieces with the "Connect" button in the physics tab helps only partially, because anyway it allows the pieces do compenetrate each other while running a physic simulation. But anyway this should not be needed, as the shape of the pieces itself should keep the model united.

I've had a look at the code, and it seems to me that the gaps are created by downscaling the pieces a bit. That's probably why increasing the gap doesn't help in this case: while indeed the studs get smaller, also the connecting piece gets smaller, so there might be no margin between them.

So, the question: would it make sense to add an option to downscale only the studs, the technical axles and a few other parts? In an ideal would the importer could detect the collisions itself and automatically decide which model parts need to be downscaled, but I guess that's far from trivial (unless Blender itself provides some function to find the collision area).

**Comment by mardy** [comment]
Yesterday I tried playing with the code to reduce the studs' size, and indeed that helped in avoiding explosions. However, the issue is not limited to studs: imagine of putting a 2x2 brick on top of a [car mudguard](https://brickset.com/parts/4600176), and you can see how unless we add some margins the brick will collide with the mudgards.
So -- maybe -- a solution might be not just to scale the mesh, but kind of "erode" a thin layer of it from all of its external faces. I actually wonder if Blender has a tool or a modifier for this; if so, then we could close this issue.

**Comment by TobyLobster** [comment]
Sadly this seems more like a physics issue rather than an importer issue. In general trying to make pieces not touch by some specified small distance seems difficult to me. Probably better than scaling the size or shape of the pieces themselves is to make a separate collision shape (manually?) that's slightly smaller than the original piece... I'm no expert on how Blender physics works though, so I don't know if this is possible.

**Comment by mardy** [comment]
I found that if you select a piece and enter edit mode, in the tools shelf in the left there's a `Shrink/Fatten` menu which does exactly what I wanted to achieve.
Shrinking the pieces a bit improves a bit the simulation, but unfortunately the result is still far from usable (the pieces still tend to fall down and vibrate for no reason), but this is clearly a Blender issue.

**Comment by TobyLobster** [comment]
Nice find on the Shrink/Fatten menu, and good luck with the physics. There are a number of options that affect physics stability, apparently: https://www.youtube.com/watch?v=TyHUgRpgw3o
