### ISSUE TITLE
Set default color for import?

### ISSUE THREAD

**Issue by elfprince13** [TobyLobster/ImportLDraw#14]
I can't figure out how to import bricks with any color other than red set to the "current color" - is there a UI element I'm missing somewhere?

**Comment by TobyLobster** [comment]
You must import a lego model, rather than an individual brick. The colour of each brick in the model is specified in the LDRAW (.ldr) model file you choose to import.

There are many ldraw models on the internet, and many software packages output ldraw models.

Alternatively Iif you are technically inclined, more information on the ldraw format can be found here http://ldraw.org/article/218.html

Thanks,
Toby

**Comment by elfprince13** [comment]
@TobyLobster - I'm deeply familiar with the format. I'm primarily interested in using Blender to convert individual parts to COLLADA for use with SceneKit, and would like to preserve color 16 (and I guess any color 24 if it showed up somewhere) through that process, so I can use it to dynamically change the color of individual parts.

Would you accept a PR with a checkbox to enable this?

**Comment by TobyLobster** [comment]
I'm not sure what you mean by 'preserve color 16'? Once a piece has been imported into Blender it only has an RGB colour, not a colour number. If you wish to set a different colour for a brick, then import a model containing that one brick, and specify the desired colour in the model.

**Comment by elfprince13** [comment]
You're creating a separate material for each color in the source model, and the names of those materials are clearly incorporating the original LDraw color codes.

It's sort of irrelevant what RGB color is used in the import, I just want to make sure that usages of the "current color" and "complement color" codes are preserved as distinct materials.

Right now 16 is getting mapped to 4 (i.e. red - http://www.ldraw.org/article/547.html), before the materials are generated.

**Comment by TobyLobster** [comment]
Ah I see what you mean now. I'm not sure this option is of general interest enough to add it as a UI option. If enough people wanted it then maybe I'd add it. If you want to make the change yourself locally, It might just be a case of changing function resolveColour in loadldraw.py.

**Comment by uncannysnake** [comment]
Of course I want that. Actually, I looked at this project/issue just because of that reason. I would be very happy if it got added.
