### ISSUE TITLE
Mesh to Geometry

### ISSUE THREAD

**Issue by uncannysnake** [TobyLobster/ImportLDraw#15]
Is it possible to import Geometry instead of Meshes?

In LDView it is possible to export to .3ds which can be opened and edited in Blender. (The problem with LDView export is that it gives our very low poly models). But since with your addon you only convert to meshes similar to an .stl file this makes editing the brick geometry afterwards pretty much impossible.

Your script puts out very nice bricks, better than anything else, so it would really be a shame if this wasn't possible.

**Comment by ali1234** [comment]
Can you explain what you mean by geometry? Or maybe attach a blend file with an example?

**Comment by TobyLobster** [comment]
I don't understand what is wanted here. Closing.
