### ISSUE TITLE
Automatic parenting of related parts

### ISSUE THREAD

**Issue by mardy** [TobyLobster/ImportLDraw#16]
This is another tricky request :-)

When importing a minifig, it would be nice if we could parent the hands to the arms, the arms to the torso, etc.; similarly, when importing a car, ideally we'd like the wheels to be parented to the piece holding them. Windows could be parented to window frames, and so on.

My idea is to have a list of relationships:
```
auto_parents = [
    ('3842', [('3626', 0, 0, 0)]), # parent helm to head
    ...
]
```
where the first item of the tuple is the child, and the second one is a list of possible parents; for each parent, we have the name of the parent piece and the x, y, z coordinates where we expect it to be found, relative to the child item.
Then the importer would look at all imported parts, and for each of them check if they are part of this list; if they are, it would go through the list of possible parents, and create a child-parent relationship to each parent found in the expected position.

If you think this could work, and if you can give me some hint on where in the code this algorithm could reside, I can try to find some time to implement it.

**Comment by TobyLobster** [comment]
I liked the idea of this feature, so I took your code and updated/iterated on it. e.g. I've put the parent-child data into a text file (parents.txt). The latest release now includes this feature as an option. I've stuck to just Minifigure parts for the moment.
