### ISSUE TITLE
horizon_color takes 3 arguments, not 4

### ISSUE THREAD

**Issue by rhester72** [TobyLobster/ImportLDraw#20]
Line 3271 (or close) reads:

scene.world.horizon_color = (1.0, 1.0, 1.0, 1.0)

This should read:

scene.world.horizon_color = (1.0, 1.0, 1.0)

Otherwise, an error is thrown by Blender and the horizon is black.

**Comment by TobyLobster** [comment]
This is now fixed in the latest release, thanks.
