### ISSUE TITLE
Slope textures don't seem to work at all in "improved slope calculations" commit

### ISSUE THREAD

**Issue by rhester72** [TobyLobster/ImportLDraw#22]
This commit:

https://github.com/TobyLobster/ImportLDraw/commit/bc21995d99e6348dceafad4c024040fe88941c5b

doesn't seem to add slope textures at all (I haven't tested the earlier commit that was supposed to do much the same thing).  I enabled the 'blue in debug' code, and on import, nothing is changed.

The most obvious example is parts 3297 and 3298 in the attached MPD:

[0497-79.zip](https://github.com/TobyLobster/ImportLDraw/files/2321624/0497-79.zip)

**Comment by rhester72** [comment]
Tested a8bd898c9eac4a2fda6a260e788116ce4f6e31d3 and it seems to work as expected, so something about the "improved" commit broke things.

**Comment by TobyLobster** [comment]
Oh that's odd, as I've double checked and it seems to work here on your model. I take it there are no errors? Any suspicious looking output on the console? Check you are using v1.1.6 of the importer. Are you zoomed in enough on the bricks to notice (I did turn down the effect).

**Comment by TobyLobster** [comment]
![lego_slopes](https://user-images.githubusercontent.com/9774304/44631353-733bfb00-a962-11e8-8c20-3930d8360995.png)

**Comment by rhester72** [comment]
No errors and nothing suspicious-looking.  Definitely using 1.1.6 from the release ZIP.  Rendering in 4K and zooming in about the same range as your clip.

Two suspicions at this case:

- Somehow, perhaps the Python script in the ZIP is older than github tip.  Checking that first.
- It could be a bug triggered by non-default options, going to experiment with that as well.

**Comment by TobyLobster** [comment]
Thanks

**Comment by TobyLobster** [comment]
FYI: I'm using Blender 2.79b

**Comment by rhester72** [comment]
Ditto - right now I'm chasing a theory that it's actually lighting-related (I normally don't use the default background.exr) but I'm trying to narrow the scope so it doesn't take so long between tests.  :)

Could you confirm for me what should happen if I uncomment the following:

                        # For debugging purposes, we can make sloped faces blue:
                        # if isSlopeMaterial:
                        #     faceColor = "1"
                        # else:
                        #     faceColor = geometry.faceColours[i]

Should the 'bumpy texture' turn blue or the entire slope face turn blue?  (i.e. will it be super-obvious?)

**Comment by TobyLobster** [comment]
Uncomment the code and change the following line to read:    
                        material = BlenderMaterials.getMaterial(faceColor, isSlopeMaterial) 
Then the sloped faces will appear blue (in the 3d view, without having to render).

**Comment by rhester72** [comment]
Thanks!

I've tested this a LOT over the last 18 hours, and can confidently say now that it's NOTABUG.

Three things led to the false report:

- My attempt to enable debugging to confirm my initial suspicion failed because I didn't realize that the index would need to be manually overridden as well :)
- My choice of an alternate and brighter EXR background results in a bit more of a 'washed out' appearance of this particular texture (located where it is)
- The reduction in strength of the texture makes it more difficult to see at distance

I may experiment with returning to the old texture to see what results that gives, but there's definitely no bug - closing.  Thanks again!
