### ISSUE TITLE
3678* should not have a textured slope

### ISSUE THREAD

**Issue by rhester72** [TobyLobster/ImportLDraw#23]
Title is the explanation - set 926 (Classic Space/Command Center) has 3678 in transparent that shouldn't be textured (and to the best of my knowledge, 3678 isn't texted in any set)

EDIT: Come to think of it, isn't it a general rule that no vertical slope in excess of 45 degrees is textured?

**Comment by TobyLobster** [comment]
Looking at photos online sometimes 3678 has a grainy texture, sometimes not (e.g. a google image search for 'lego 3678' ignoring the CG images, some photos the grain is clearly there). It does look like there's a difference between 3678a and 3678b where b has the bottom tube and grainy slope, but 3678a doesn't. https://rebrickable.com/parts/3678a/slope-65-2-x-2-x-2-smooth-without-bottom-tube/ 

I'll have to do some more research to figure this out more fully.

**Comment by rhester72** [comment]
You nailed it, actually - per BrickLink, Rebrickable and Bricker, 3678a (without tube) is smooth and 3678b (with tube) is indeed textured.

Given the way the script currently ignores differentiators, if you make the selector 3678b like this:

    '3678b':{24},

will that work?

**Comment by BertVanRaemdonck** [comment]
Good catch on finding that error! It should be an easy fix: in the isSlopePart function in loadldraw.py, simply include a separate case that returns False for 3678a.

**Comment by rhester72** [comment]
Rather than special-casing individual parts as if/then type scenarios, I was thinking structurally it would be better if the hardcoded list of textured slope parts can be extended to allow extensions (like the "a")  which would allow for cleaner code and more flexibility in the future.

**Comment by BertVanRaemdonck** [comment]
Fair enough. A downside would be that the dictionary would become bigger by including all the part variants, unless the code is altered to first search for an "exact" match of the part name in the dictionary, and only if that doesn't yield any results, would resort to searching for the part number (ignoring variations). With the quotation marks, I mean that both the part number and the letter indicating the variation should match and not any indication for decorations, because then the dictionary would become very unwieldy.

**Comment by rhester72** [comment]
Well, I say that with little to no understanding of Python - I assumed it would be a simple matter to iterate a start-of-substring list (and naively assumed that's what it was in the beginning).  I'll stay out of the implementation particulars, then.  =)

**Comment by TobyLobster** [comment]
Fixed in latest release, thanks.
