### ISSUE TITLE
Request for lighted parts

### ISSUE THREAD

**Issue by rhester72** [TobyLobster/ImportLDraw#25]
Would it be possible to add (optional/toggle) support for lighted bricks, specifically 98785:

https://brickset.com/parts/design-98785

(ideally in LDRAW color 36)

My old POV-Ray Radiosity scripts supported this, and it's amazing how much difference the subtle effect can make, particularly with (deliberately) darker lighting/environments.

If you consider the request, please continue your focus on realism - not looking for this to turn out to be some sort of high-intensity headlight, ideally it should be presented as accurately to life as possible.

**Comment by TobyLobster** [comment]
I have added support for light bricks in the latest release (1.1.9).

**Comment by rhester72** [comment]
Thank you so much for this - tested and working beautifully!
