### ISSUE TITLE
Artifacts on technic side holes.

### ISSUE THREAD

**Issue by ali1234** [TobyLobster/ImportLDraw#26]
The side holes have a weird square around them. I left all the import options at defaults. Example:

![technicside](https://user-images.githubusercontent.com/651970/47610411-41bbda80-da4c-11e8-935e-4a99f12a86b1.png)

**Comment by ali1234** [comment]
This is caused by non-manifold geometry in the LDraw parts.

**Comment by ali1234** [comment]
I have the beginnings of an algorithm for fix these errors:

```
        def fixone():
            for e1 in bm.edges:
                if len(e1.link_faces) == 1:
                    for v in e1.verts:
                        for e2 in v.link_edges:
                            if e2 is not e1 and len(e2.link_faces) == 1:
                                v1 = e1.other_vert(v)
                                v2 = e2.other_vert(v)
                                vec1 = v1.co - v.co
                                vec2 = v2.co - v.co
                                if (vec2.length - vec1.length) > 0.001 and vec1.angle(vec2) < 0.02:
                                    p = v1.co
                                    result = bmesh.ops.subdivide_edges(bm, edges=[e2], cuts=1)
                                    result['geom'][0].co = p
                                    bmesh.ops.remove_doubles(bm, verts=bm.verts[:], dist=globalWeldDistance)
                                    return True
            return False

        count = 0

        while fixone():
            count += 1
        print(count)
```

I do this at the end of addSharpEdges()

It checks every pair of connected, open edges. If they are co-linear and one is shorter than the other, it subdivides the longer one and moves the new point to the far vertex of the shorter one. Then it removes doubles. It is run over and over until there are no more co-linear edges.

This algorithm is not efficient at all and it loses the edge metadata for bevel/sharp/crease etc. It does fix the artifacts and the result is good if I manually fix the edge metadata.

**Comment by ali1234** [comment]
I rewrote this to suck less and here is the result:

![image](https://user-images.githubusercontent.com/651970/48082232-f216a500-e1e9-11e8-843c-23565b06c063.png)

Now the 3455 arch is almost subsurf compatible. It still has some problems but they are not visible. The technic pieces still have many problems with subsurf but the artifacts are gone.

**Comment by TobyLobster** [comment]
Hi ali, this is looking promising, nice work. Are there issues remaining to be dealt with (performance; losing edge metadata; more subsurface fixes; anything else?).

**Comment by ali1234** [comment]
This increases import time for the tower bridge model from 44 seconds to 48 seconds.

Edge metadata is properly preserved now.

There are still problems with subsurf and bevel but they seem to be inherent to how the operations work. I don't know if they can be fixed at all.

**Comment by ali1234** [comment]
The remaining subsurf problems are described quite well by this question: https://blender.stackexchange.com/questions/98369/how-to-get-rid-of-subsurf-overhangs

I'm investigating ways to automatically mitigate this now.

**Comment by ali1234** [comment]
I've now squashed the last few metadata problems. Unfortunately due to edges being connected which were not before, I ran in to this bug: https://developer.blender.org/T57691

The effect is that turning on clamp overlap on most pieces causes the bevel to be clamped down to nothing on all edges. But turning off clamp overlap may lead to artifacts in some places.

Subsurf is still not completely reliable, but it is getting closer for simple pieces.

**Comment by ali1234** [comment]
Here is 3701 with bevel, no clamp, and subsurf:

![newsubsurf](https://user-images.githubusercontent.com/651970/48185196-327e3c00-e32c-11e8-9c15-a2a7df4c6804.png)

It's close but there is still a small artifact. Extra beveling canbe used to hide that, but it is difficult to automatically decide where to place the extra bevel weights.

**Comment by ali1234** [comment]
![space](https://user-images.githubusercontent.com/651970/48188387-95c09c00-e335-11e8-8b40-5ec8a3ec8e45.png)

On this minifig, subsurf has excellent results on the helmet, okay results on the hands, and it is a complete disaster on the body.

Also it shows another metadata bug: I'm not copying face colours.

**Comment by ali1234** [comment]
Materials are copied now. Found another bug though:

![screenshot_2018-11-08_14-10-43](https://user-images.githubusercontent.com/651970/48203721-26ac6d00-e360-11e8-8ec5-b88a9b5eb43b.png)

Bevel has not been applied to the edge nearest the camera. All the other edges are okay. I thought this was a bug in my code, but the screenshot above has my stuff disabled.

**Comment by ali1234** [comment]
Per https://developer.blender.org/T57691 it looks like you will have to turn off clamp overlap in addModifiers in order to have consistent sized bevels with edge merging - at least until the bevel modifier gets rewritten.
