### ISSUE TITLE
StudVersion 4 missing vertices

### ISSUE THREAD

**Issue by stefaaaaan** [TobyLobster/ImportLDraw#3]
First of all: awesome tool, mate!
I was waiting for something like this for years.
Finally, there is an easy way to use ldraw models in modern 3d packages.
Thank you so much! :)

But there seems to be an issue with StudVersion 4. See image below.
I changed the script to test 3 and 5, which seems to work fine. But, version 4 seems to be the best choice if one wants to render high-quality close-ups
Any ideas?
I don't know much about blender. It's a fresh 2.77 install.

![legoblender](https://cloud.githubusercontent.com/assets/13545087/16179056/d457c072-365a-11e6-8015-50b5efe3f189.jpg)

**Comment by TobyLobster** [comment]
That's odd. I'm using 2.77 too, and it's working fine here. Could be the combination of settings you're using is throwing up an issue, or maybe it's an issue that only appears on Windows (I'm using Mac, looks like you're on Windows from the screenshot). You can restore to the default settings with 'Operator Presets -> Restore Defaults' when importing. Then check the 'Use LEGO logo on Studs' option of course. If that still fails, I'll have to recheck on Windows to see if there's an issue there.

**Comment by stefaaaaan** [comment]
Hey Toby, 
thank you for getting back to me.
I restored the settings, the result was the same. Yes, it's Windows 10. Maybe I'm able to test it on a Mac on the weekend.

**Comment by TobyLobster** [comment]
Hi Stefan,
I found and fixed the stud issue (which turned out to be a missing file) and have released a new version. Let me know how you get on with it. 

Thanks, Toby

**Comment by stefaaaaan** [comment]
Hey Toby,
it works great now! Thank you for looking into this.
Again, awesome tool! I'll spread the word.
Have a nice rest of the weekend :)

Stefan
