### ISSUE TITLE
Update to Blender 2.8

### ISSUE THREAD

**Issue by knightknight** [TobyLobster/ImportLDraw#35]
Will this be getting an update to Blender 2.8?

**Comment by TobyLobster** [comment]
Yes :-) It's available now in the latest release (1.1.9)

**Comment by Symbian9** [comment]
Please, also create branch for Blender 2.79.x

**Comment by TobyLobster** [comment]
@Symbian9 Good idea - done.

**Comment by bskaggs** [comment]
I had to make a few more changes to get things to work in the latest beta.  See #41 .

**Comment by TobyLobster** [comment]
Merged with thanks.
