### ISSUE TITLE
Importing of grouped pieces

### ISSUE THREAD

**Issue by mardy** [TobyLobster/ImportLDraw#4]
Hi there, and thanks for this wonderful add-on!

I'm rather new to both `blender` and `leocad`, so I'm not even sure whether this request makes much sense. If it doesn't, just please tell me :-)

In `leocad` you can group pieces by selecting them and pressing `Ctrl+G`. This can be used to group together a wheel with its tire, or a minifig's arm with the corresponding hand. As far as I can tell, these still get imported as two totally separate pieces in blender.

Would it be possible to import them by preserving the group? I'm new to blender, so I'm not even sure what would be the correct form of importing them: whether a parent-object relationship, or a constraint, or something else.

**Comment by mardy** [comment]
Or maybe creating an extra empty object for the group, which would act as parent for all the items in the group?

**Comment by TobyLobster** [comment]
Hi @mardy that makes perfect sense. I have just released a new version that includes this feature. It creates empty objects for LeoCAD groups as you suggest. Enjoy!

**Comment by mardy** [comment]
Thanks Toby, that's excellent! I'll test this soon!
