### ISSUE TITLE
SyntaxError when activating ImportLDraw in Blender

### ISSUE THREAD

**Issue by Sieje** [TobyLobster/ImportLDraw#40]
I have Blender working fine on my Windows 10 Pro x64 PC. After importing ImportLDraw, I click to activate it and receive a SyntaxError (see screenshot, attached). ImportLDraw does not activate. I downloaded ImportLDraw directly from:
https://github.com/TobyLobster/ImportLDraw

![ScreenShot961](https://user-images.githubusercontent.com/50999573/58346380-603a5680-7e20-11e9-87b0-0018545ebfe3.png)

**Comment by TobyLobster** [comment]
The Blender 2.79 version of the importer can now be found in the blender279 branch.

**Comment by Sieje** [comment]
I can now activate the 2.79 version in Blender. Thanks so much!

**Comment by bluespace** [comment]
sorry but i have the same problem but i don't understand how you solve it. can you explain better pls.

**Comment by Sieje** [comment]
The solution for me was to download and use the new 2.79 version of the importer which TobyLobster recently added to the blender279 branch.

**Comment by Sieje** [comment]
To bluespace:
The solution for me was to download and use the new 2.79 version of the importer which TobyLobster recently added to the blender279 branch, which I found here:
https://github.com/TobyLobster/ImportLDraw/tree/blender279
YMMV. It may depend on what version of Blender you have.

**Comment by bluespace** [comment]
To Sieje:
Oh okay, i was in master branch. now i understand and it works. Thank you very much
