### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Chieftain24** [TobyLobster/ImportLDraw#52]
![2019-11-08](https://user-images.githubusercontent.com/57546668/68515376-a2454080-0278-11ea-87a5-37820156f89f.png)

Hi, I get this error when I try to activate the addon after installation. Don't know if I'm being stupid but any help is appreciated.

Thanks

**Comment by TobyLobster** [comment]
It looks like you are using Blender 2.79. If upgrading to Blender 2.81 does not suit you, then you can still download an older release of the add-on for Blender 2.79 from https://github.com/TobyLobster/ImportLDraw/releases/tag/1.1.9.
