### ISSUE TITLE
Error when importing - color assignment issue in script ? 

### ISSUE THREAD

**Issue by blambert3d** [TobyLobster/ImportLDraw#53]
Error when importing - sequences of dimension 0 should contain 3 items, not 4 

the line the error is occurring on is 1802

![2019-11-21 23_03_44-Blender](https://user-images.githubusercontent.com/58054046/69384248-b430d580-0cb3-11ea-9717-2927876459b8.png)

            material.diffuse_color = getDiffuseColor(col["colour"])

Blender version 2.80 windows 
LDraw made from LCAD

**Comment by cuddlyogre** [comment]
I've written my own importer that you may find useful. https://github.com/cuddlyogre/ExportLdraw

**Comment by TobyLobster** [comment]
Fixed in latest release.
