### ISSUE TITLE
Linux is supported

### ISSUE THREAD

**Issue by Symbian9** [TobyLobster/ImportLDraw#56]
> **Mac** and **Windows** supported (and hopefully **Linux**, but this is currently untested)

Fix your `README.md`: Linux **supported** too. Tested ;-)

- https://www.reddit.com/r/lego/comments/d666xd/micropolis_mallet_locomotive_0880/

![pic.1](https://i.imgur.com/VBLIbUn.png)

**Comment by TobyLobster** [comment]
That's a sweet micro-train. Thanks for testing!

**Comment by hobeika** [comment]
I confirm it works on Debian GNU/Linux.
Thanks for this great add-on.

**Comment by bb1950328** [comment]
Works on Ubuntu 20.10 too

**Comment by TobyLobster** [comment]
Thanks.

**Comment by Genkds** [comment]
Can confirm works with Blender 2.93.5 in Fedora 34.
