### ISSUE TITLE
pink colouring to scene when rendering

### ISSUE THREAD

**Issue by JMUDoc** [TobyLobster/ImportLDraw#57]
LDraw models import correctly but all renders have a pink colouring to them, as though the light were pink, even when the light and the included LDraw ground place are deleted; see attached render.
![5580](https://user-images.githubusercontent.com/59938390/72473861-7d70ca80-37df-11ea-93c1-52f698e30b30.jpg)
Affects Cycles and Eevee engines, but not Workbench, in both CUDA and CPU modes.
Also affects "render preview" viewport shading in Layout mode.

Using Blender 2.81 and the latest master of ImportLDraw.

Many thanks in advance for any advice/fixes.

**Comment by JMUDoc** [comment]
It looks like this could be to do with missing textures... any ideas?

**Comment by mikearney** [comment]
Yes this is a missing texture file. Whenever you see this bright magenta in Blender it means it can't find a linked texture

**Comment by cuddlyogre** [comment]
If I had to guess you haven't downloaded loadldraw/background.exr.
