### ISSUE TITLE
Feature Request: Option to import .dat without studs to .obj

### ISSUE THREAD

**Issue by tysonggraham** [TobyLobster/ImportLDraw#60]
I wanted to start off by saying I'm very impressed with this module! Very robust code, nice work! 

I need to export LDRAW .dat files into .obj for use with a Unity Game Engine application. In addition, I am using physics simulation as part of my project and will require realistic snapping of blocks. The best method for this has proven out to be creating a separate .obj of the block WITHOUT studs. This allows snapping the studs inside of the ports of lego blocks.

This module seems like the perfect tech enabler for this feature.

**What:**
- Export .dat file with studs <filename>.obj  - (As object file)
- Export .dat without studs <filename>-c.obj - (As collision file)

**Why:**
- .dat file not interpreted by game engine. .obj filetype needed.
- Collision file needed for game engine use. Accurate snapping of Lego blocks.

**Comment by youluckyfox** [comment]
Yes please. I intend to create a VR environment to stack models together. To use this in unity I need a separate collision file that doesn't have studs. I would love a quick way of selecting an LDRAW model and automatically exporting a .obj with and without studs.

**Comment by TobyLobster** [comment]
This is beyond the scope of this importer.
