### ISSUE TITLE
Colour import issue

### ISSUE THREAD

**Issue by Unpixelled** [TobyLobster/ImportLDraw#68]
I installed it correctly but when importing models, all materials end up as being a Lego Standard yellow, parts that had the same colour (ie two black parts for example) did share the same material but all were the standard yellow. I attempted to change my import settings and new Ldraw models but none of that worked.

A friend who correctly installed it tried to assist and sent me his version but the same issue occured. (I don't use Github a lot so I may be pointing out something obvious I've missed or that it's an issue with my Blender rather than the plugin but I don't know enough to find a fix).

**Comment by dominikbucher** [comment]
Turns out in my case it was a wrongly exported ldraw parts library that was missing the colors file (or rather the `LDConfig.ldr` file). So if it helps anyone, make sure that this file is exported correctly and the paths are set properly.

**Comment by Unpixelled** [comment]
> Turns out in my case it was a wrongly exported ldraw parts library that was missing the colors file (or rather the `LDConfig.ldr` file). So if it helps anyone, make sure that this file is exported correctly and the paths are set properly.

Where should this file be placed in order for it to be corrected?

**Comment by TobyLobster** [comment]
As this appears to be an issue with the ldraw parts directory, I will close.
