### ISSUE TITLE
Batch rendering with different colors

### ISSUE THREAD

**Issue by darkcristle** [TobyLobster/ImportLDraw#71]
Hello!

I am currently trying to batch render a large amount of individual pieces in the various colors that they come in.  I am not very experienced in blender so maybe I am missing something obvious.  I am having issues with figuring out how to import the pieces in colors other than the default red.  Has anyone else had any success with this?

Thank you!

**Comment by RagingRoosevelt** [comment]
You need to import an LDraw file specifying the color you want.  For instance, if you wanted to open [part 3004](https://brickset.com/parts/design-3004) in black (color code `0`), you'd need a `.LDR` file with the contents (first line is just a comment)


```
0 // 3004--Black
1 0 0 0 0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 3004.dat
```

The line that starts with a `1` is a ["Line Type 1"](https://www.ldraw.org/article/218.html#lt1) (aka "sub-file reference").  If you know the part number and the LDraw color code, you can just sub out the second token (the first `0`) with whatever color code you want and sub out the `3004.dat` with `{partnumber}.dat` for whatever part number you want.  

You can view the color code definitions in the `LDConfig.ldr` file in the [library download](https://library.ldraw.org/updates).
