### ISSUE TITLE
Instructions Look: 'RenderSettings' object has no attribute 'alpha_mode'

### ISSUE THREAD

**Issue by brianlow** [TobyLobster/ImportLDraw#76]
I think the loader is failing silently near the end of [setInstructionsLook()](https://github.com/TobyLobster/ImportLDraw/blob/ed7eeb7761b5cbf3226a55275b2881a13c933b4c/loadldraw/loadldraw.py#L3891):
```python
def setupInstructionsLook():
    # ...

    # This line is failing with:
    #     AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'
    #
    # This attribute doesn't appear in the latest 3.5 docs:
    #     https://docs.blender.org/api/current/bpy.types.RenderSettings.html
    render.alpha_mode = 'TRANSPARENT'

    # ...
```

I noticed this when running Blender from the terminal:

```bash
# launch and run the import via Blender File -> Import
/Applications/Blender.app/Contents/MacOS/Blender

# launch script to automatically render a brick
/Applications/Blender.app/Contents/MacOS/Blender --background --python my-script-to-render-lego.py
```

Move evidence: the add-on continues to work if I change the offending line to an early `return` and use the importer normally via Blender File -> Import

Is the rest of setupInstructionsLook() needed? If not would you be open to a PR? I am building a script to render parts and it fails here. Update: I noticed it is missing white lines on black parts

Details:
* Blender Version 3.5.0 (3.5.0 2023-03-29)
* MacOS 13.3.1 (22E261)

**Comment by brianlow** [comment]
Commenting out the offending line so rest of setupInstructionsLook() is run:

* transparent parts not rendered
* lines extend past edge of part
* stud tops don't have full circlr

    <img width="752" alt="image" src="https://github.com/TobyLobster/ImportLDraw/assets/938138/37f5ff9c-c5e2-4fc9-9b7b-c12535e5a3d3">




Early `return` so most of setupInstructionsLook() doesn't run:

* missing white lines on black parts
* missing edge on sloped brick

    <img width="811" alt="image" src="https://github.com/TobyLobster/ImportLDraw/assets/938138/032ce5a2-52e9-4748-b335-b33542a02dad">

**Comment by TobyLobster** [comment]
Thanks for the report - this should now be fixed with the latest release.

**Comment by brianlow** [comment]
Looks good, thanks!
