### ISSUE TITLE
Set LdrawLibrary path via Python

### ISSUE THREAD

**Issue by Maxinger15** [TobyLobster/ImportLDraw#77]
Hi,

is there a way I can set the Path to the LDraw Library as described in the Readme via python.
I want to run blender headless in a docker container so no gui interaction is possible.

**Comment by TobyLobster** [comment]
You can configure and run the importer using something like the script below. You'll need to change the filepaths of course.

[auto_lego.py.txt](https://github.com/TobyLobster/ImportLDraw/files/11661569/auto_lego.py.txt)
