### ISSUE TITLE
Scale question

### ISSUE THREAD

**Issue by bjornsyse** [TobyLobster/ImportLDraw#80]
Hi

When I import ldraw files exported from stud.io, I do not get them into Blender in the correct scale. I've tried with this 3005 part which according to Wikipedia would have dimension of 7.8mm in width. However it comes into Blender as 20 units (meter in my case). Import scale setting is set to 1.0. 

Is there some type of inch/mm factor at work herer? 20 / 2.54 is 7.87, which is quite close to 7.8 at least. 

https://en.wikipedia.org/wiki/File:Lego_dimensions.svg

![image](https://github.com/TobyLobster/ImportLDraw/assets/26255606/6ba4454d-3d83-4c26-80f8-9631c0d69f2d)

![image](https://github.com/TobyLobster/ImportLDraw/assets/26255606/0a5cf9bb-a7b9-431f-8928-df23b8e2071d)

**Comment by TobyLobster** [comment]
You are right that the default scaling results in large bricks. This is really just for historical reasons with the importer. It would be disruptive to change that default now I think. The default scale factor is 0.01, but if you use 0.0039 this should import the parts at the correct size.

**Comment by bjornsyse** [comment]
Hi

Thanks for looking into it. Seems odd to leave it at such an arbitrary default scale factor but I suppose you have your reasons. Maybe the readme could be updated to inform about the 0.0039 natural constant :) 

Scale is quite important if one is working with 3D printing, but even for rendering/animation engines nowadays it's crucial to get it correct in order for lens values or simulation gravity dependent things to work right.

**Comment by TobyLobster** [comment]
Yeah, I am in two minds about it. The downside to fixing it is that people that have already imported models will have new imports at a different scale, which will be unexpected. It does kinda feel right to fix it though, so maybe I will.

**Comment by bjornsyse** [comment]
I understand. Well I suppose the read me would have to mention the scale factory anyhow. Perhaps you could add something to the interface in blender palette giving you the option to apply “legacy scale” and then the scale field would change to 0.0039 Hälsningar Björn--Björn SyseSyse Digital Design ABwww.syse.se+46 706281244On 7 Jun 2023, at 20:17, Toby Nelson ***@***.***> wrote:﻿
Yeah, I am in two minds about it. The downside to fixing it is that people that have already imported models will have new imports at a different scale, which will be unexpected. It does kinda feel right to fix it though, so maybe I will.

**Comment by TobyLobster** [comment]
Fixed in latest release. Now a scale factor of 1 is the default which means: import at real life scale.
