### ISSUE TITLE
Missing files problem

### ISSUE THREAD

**Issue by AlexWots** [TobyLobster/ImportLDraw#81]
when i try to import the model in blender i get the following problems. I tried to completely reinstall both the addon and the program itself
![Знімок екрана 2023-06-06 193357](https://github.com/TobyLobster/ImportLDraw/assets/135738300/cb3b4509-79c8-4331-8494-80fff8e16247)
![Знімок екрана 2023-06-06 193411](https://github.com/TobyLobster/ImportLDraw/assets/135738300/8335c7ee-47cb-4bd8-b3b5-d2c453e770ae)

**Comment by TobyLobster** [comment]
This will happen if you have not downloaded and set up the correct directory that contains the lego parts. The instructions are at https://github.com/TobyLobster/ImportLDraw In particular see the section 'Setting the LDraw Parts Library directory' for more information.

**Comment by AlexWots** [comment]
Problem that i did it

**Comment by TobyLobster** [comment]
Just to check: (1) Your ldraw directory should contain subdirectories 'models' 'p' and 'parts' for example. (2) The parts subdirectory should have lots of numbered files ending in '.dat'. And (3) you specified the full path to your draw directory in the settings when choosing a model file to open.

**Comment by AlexWots** [comment]
exactly 
![image](https://github.com/TobyLobster/ImportLDraw/assets/135738300/52b7ec37-7a3b-4a02-b9db-e193f49ea7c0)
it looks like this path to my folder

**Comment by TobyLobster** [comment]
I wonder if it is having trouble because of the quotation marks and space in the path to the ldraw directory. If you have  a moment could you try a path without spaces?

**Comment by AlexWots** [comment]
OMG i spend all day for this shit a realy thankfull. You now my God and I am ready to kiss you
