### ISSUE TITLE
Importing into Blender 3.51

### ISSUE THREAD

**Issue by chriskiepfer** [TobyLobster/ImportLDraw#82]
I am having an issue importing DAT files into Blender 3.51. It seemed to work fine in 3.5?
Any suggestions to fix this would be appreciated.

**Comment by TobyLobster** [comment]
Try the latest release. That works here. https://github.com/TobyLobster/ImportLDraw/releases/tag/v1.1.17

**Comment by chriskiepfer** [comment]
Thanks for the reply, I have reinstalled and downloaded the l draw files again and I am having some success.  I noticed that when importing a plate, I am not seeing any details underneath the plate? Is that normal?
Another question, how does the import assign color and material to the part in blender, I see nothing in the . DAT file?
If you can help that would be great.
Thanks
Chris

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TobyLobster** [comment]
...and the ground plane may be covering the underneath of the piece?

**Comment by chriskiepfer** [comment]
Hi
I figured out the categories, so ignore my email.
Chris

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TobyLobster** [comment]
Yay, glad you got it working :-)
