### ISSUE TITLE
Double sRGB -> linear RGB conversion

### ISSUE THREAD

**Issue by brianlow** [TobyLobster/ImportLDraw#83]
When reading the LDRConfig file in `__readColourTable`, I think colors are are transformed twice:

https://github.com/TobyLobster/ImportLDraw/blob/b1490ebd42f3b2f5069884e8e677a9355530880f/loadldraw/loadldraw.py#L670

https://github.com/TobyLobster/ImportLDraw/blob/b1490ebd42f3b2f5069884e8e677a9355530880f/loadldraw/loadldraw.py#L836-L838

if the `lgeo` overrides are specified in sRGB, then perhaps the first conversion shouldn't be done so that the second conversion will also catch the overrides.

**Comment by brianlow** [comment]
**Concrete example**

I've tweaked my LDRConfig so blue is `#003DA5`
```
0 !COLOUR Blue                                                  CODE   1   VALUE #003DA5   EDGE #333333
```
I import a single brick model using Blue:
```
0 Untitled Model
0 Name:  UntitledModel
0 Author:
0 CustomBrick
1 1 30.000000 -24.000000 -20.000000 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000 3002.dat
```

**Expected**: the shader base color matched LDRConfig at `#003DA5` or linear `(0, 0.04, 0.37)`

**Actual**: the shader base color is considerably darker at `#000C60` or linear `(0, 0, 0.12)`

**Comment by TobyLobster** [comment]
Thanks - now fixed in latest release.
